create table
  public.DailyStats (
    id bigint generated by default as identity not null,
    created_at timestamp with time zone null default now(),
    date date null,
    region character varying null,
    total_trails bigint null,
    total_distance numeric null,
    total_duration character varying null,
    constraint DailyStats_pkey primary key (id)
  ) tablespace pg_default;