create table
  public.Trails (
    id bigint generated by default as identity not null,
    created_at timestamp with time zone null default now(),
    region character varying null,
    name character varying null,
    category character varying null,
    distance numeric null,
    difficulty character varying null,
    ranking numeric null,
    author character varying null,
    trail_id numeric null,
    duration numeric null,
    new boolean null,
    author_id numeric null,
    lang text null,
    date_created timestamp with time zone null,
    date_lastModified timestamp with time zone null,
    date_firstPublish timestamp with time zone null,
    region_name text null,
    district_name text null,
    customarea text null,
    constraint Trails_pkey primary key (id)
  ) tablespace pg_default;